"""Deterministic stub generator for development and testing."""

from __future__ import annotations

from textwrap import dedent

from .base import TextGenerator


class StubTextGenerator:
    """Simple stub that produces structured placeholder content."""

    def __init__(self, signature: str = "Papito Mamito Stub Engine") -> None:
        self.signature = signature

    def __call__(self, prompt: str, *, temperature: float = 0.7, max_tokens: int = 1024) -> str:
        header = f"Generated by {self.signature} | temp={temperature} | max_tokens={max_tokens}"
        body = dedent(
            """
            This is placeholder content produced by the stub generator.
            Integrate your preferred LLM client (e.g., OpenAI, Anthropic, Azure)
            to unlock Papito's full autonomous creativity.
            """
        ).strip()
        return f"{header}\n\nPrompt Received:\n{prompt}\n\n{body}"
